version: '3.8'
services:
  mongodb:
    image: "mongo"
    container_name: mongodb
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017" 
    networks:
      - zzz

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - DATABASE=mongodb://mongodb:27017/MusicZoness
    networks:
      - zzz

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - zzz
    depends_on:
      - backend

networks:
  zzz:
volumes:
  data:
  logs:
      
      